//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.14 at 05:35:16 PM JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://helloworld.sample.my/writer/")
package my.sample.helloworld.writer;
